import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Legal Disclaimer — BetBrain',
  description: 'Legal disclaimer and terms of use for BetBrain sports analytics platform.',
}

const sections = [
  {
    id: 'not-advice',
    heading: 'Not Financial or Gambling Advice',
    body: 'BetBrain provides sports analytics and data-driven insights for informational and entertainment purposes only. Nothing on this platform constitutes financial advice, gambling advice, or a recommendation to place any wager. All analysis, predictions, and insights are generated by AI and statistical models and should not be relied upon as the sole basis for any betting decision.',
  },
  {
    id: 'no-guarantee',
    heading: 'No Guarantee of Results',
    body: 'Past performance, whether real or simulated, does not guarantee future results. Sports outcomes are inherently unpredictable. BetBrain makes no warranties or representations regarding the accuracy, completeness, or reliability of any analysis, signal, or insight provided on this platform.',
  },
  {
    id: 'not-sportsbook',
    heading: 'Not a Sportsbook',
    body: 'BetBrain is not a sportsbook, bookmaker, or gambling operator. We do not accept, facilitate, or process any wagers or bets. We do not hold customer funds. Odds displayed on this platform are sourced from third-party APIs and are shown for comparison purposes only.',
  },
  {
    id: 'ai-content',
    heading: 'AI-Generated Content',
    body: 'Analysis and insights on BetBrain are generated using artificial intelligence (Anthropic Claude). While we strive for accuracy, AI-generated content may contain errors, inaccuracies, or biases. Users should exercise their own judgment and conduct independent research before making any decisions.',
  },
  {
    id: 'third-party-data',
    heading: 'Third-Party Data',
    body: 'BetBrain sources data from third-party APIs including The Odds API and balldontlie. We are not responsible for the accuracy, availability, or timeliness of third-party data. Data may be cached and could be delayed or outdated.',
  },
  {
    id: 'liability',
    heading: 'Limitation of Liability',
    body: 'To the maximum extent permitted by law, BetBrain and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use this platform, including but not limited to any losses incurred from betting decisions made using information provided on this platform.',
  },
  {
    id: 'age',
    heading: 'Age Restriction',
    body: 'BetBrain is intended for users who are 21 years of age or older (or the legal gambling age in their jurisdiction). By using this platform, you confirm that you meet the applicable age requirement and that online sports betting is legal in your jurisdiction.',
  },
  {
    id: 'changes',
    heading: 'Changes to This Disclaimer',
    body: 'We reserve the right to modify this disclaimer at any time. Continued use of BetBrain after changes constitutes acceptance of the updated terms.',
  },
]

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 font-sans">

      {/* Nav */}
      <nav className="border-b border-zinc-800 bg-zinc-950/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link
            href="/"
            className="text-base font-semibold tracking-tight text-white hover:text-zinc-300 transition-colors"
          >
            BetBrain
          </Link>
          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="text-sm text-zinc-400 hover:text-zinc-100 transition-colors px-3 py-1.5"
            >
              Log In
            </Link>
            <Link
              href="/signup"
              className="text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white px-3.5 py-1.5 rounded-md transition-colors"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Page content */}
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-14 sm:py-20">

        {/* Header */}
        <div className="mb-10 pb-8 border-b border-zinc-800">
          <p className="text-xs font-medium text-indigo-400 uppercase tracking-wider mb-3">
            Legal
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight mb-3">
            Disclaimer
          </h1>
          <p className="text-sm text-zinc-500">
            Last updated: March 14, 2026
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-10">

          {sections.map((section) => (
            <section key={section.id} id={section.id}>
              <h2 className="text-base font-semibold text-white mb-2">
                {section.heading}
              </h2>
              <p className="text-sm text-zinc-400 leading-relaxed">
                {section.body}
              </p>
            </section>
          ))}

          {/* Responsible Gambling — custom markup for the resource list */}
          <section id="responsible-gambling">
            <h2 className="text-base font-semibold text-white mb-2">
              Responsible Gambling
            </h2>
            <p className="text-sm text-zinc-400 leading-relaxed mb-4">
              Gambling involves risk and should be approached responsibly. Never bet more than you can afford to lose. If you or someone you know has a gambling problem, please contact:
            </p>
            <ul className="space-y-2.5">
              <li className="flex items-start gap-2.5">
                <span className="mt-0.5 w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0 mt-[7px]" />
                <span className="text-sm text-zinc-400">
                  <span className="text-zinc-200 font-medium">National Problem Gambling Helpline:</span>{' '}
                  <a
                    href="tel:18005224700"
                    className="text-indigo-400 hover:text-indigo-300 transition-colors"
                  >
                    1-800-522-4700
                  </a>
                </span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="mt-0.5 w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0 mt-[7px]" />
                <span className="text-sm text-zinc-400">
                  <span className="text-zinc-200 font-medium">National Council on Problem Gambling:</span>{' '}
                  <a
                    href="https://ncpgambling.org"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-indigo-400 hover:text-indigo-300 transition-colors"
                  >
                    ncpgambling.org
                  </a>
                </span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="mt-0.5 w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0 mt-[7px]" />
                <span className="text-sm text-zinc-400">
                  <span className="text-zinc-200 font-medium">Gamblers Anonymous:</span>{' '}
                  <a
                    href="https://gamblersanonymous.org"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-indigo-400 hover:text-indigo-300 transition-colors"
                  >
                    gamblersanonymous.org
                  </a>
                </span>
              </li>
            </ul>
          </section>

          {/* Contact */}
          <section id="contact">
            <h2 className="text-base font-semibold text-white mb-2">
              Contact
            </h2>
            <p className="text-sm text-zinc-400 leading-relaxed">
              For questions about this disclaimer, contact us at{' '}
              <a
                href="mailto:legal@betbrain.ai"
                className="text-indigo-400 hover:text-indigo-300 transition-colors"
              >
                legal@betbrain.ai
              </a>
            </p>
          </section>
        </div>

        {/* Back to home */}
        <div className="mt-14 pt-8 border-t border-zinc-800">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-zinc-300 transition-colors group"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="group-hover:-translate-x-0.5 transition-transform"
              aria-hidden="true"
            >
              <path d="M19 12H5" />
              <path d="M12 19l-7-7 7-7" />
            </svg>
            Back to home
          </Link>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-zinc-800">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-10">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-6">
            <div className="max-w-lg">
              <div className="text-sm font-semibold text-white mb-2">
                BetBrain
              </div>
              <p className="text-xs text-zinc-600 leading-relaxed">
                BetBrain provides analytics and insights only. We do not
                facilitate gambling or accept wagers of any kind. All content is
                for informational purposes only and does not constitute financial
                or gambling advice. If you or someone you know has a gambling
                problem, call{' '}
                <span className="text-zinc-500">1-800-GAMBLER</span>.
              </p>
            </div>
            <nav className="flex flex-row sm:flex-col gap-3 sm:gap-2 text-sm shrink-0">
              <Link
                href="/dashboard"
                className="text-zinc-500 hover:text-zinc-300 transition-colors"
              >
                Dashboard
              </Link>
              <Link
                href="/login"
                className="text-zinc-500 hover:text-zinc-300 transition-colors"
              >
                Log In
              </Link>
              <Link
                href="/signup"
                className="text-zinc-500 hover:text-zinc-300 transition-colors"
              >
                Sign Up
              </Link>
            </nav>
          </div>
          <div className="mt-8 pt-6 border-t border-zinc-900 text-xs text-zinc-700">
            &copy; {new Date().getFullYear()} BetBrain. Analytics and insights only.
          </div>
        </div>
      </footer>
    </div>
  )
}
